-- System update notification: 2026-04-27
-- Run in Supabase SQL Editor. Idempotent per company+ref_id.
-- Detailed release items are loaded from public/data/releases/2026-04-27.json.

INSERT INTO public.staff_notifications (company_id, type, title, message, link, ref_id)
SELECT
  c.id,
  'system_update',
  $t${"en":"System update — Apr 27, 2026","ru":"Обновление системы — 27.04.2026","lv":"Sistēmas atjauninājums — 27.04.2026."}$t$,
  $m${"en":"• Release news: choose the news language directly in the update pop-up, separately from the interface language.\n• Supplier invoices: match uploaded supplier invoices to real order services, mark periodic/not-required services, and see completeness directly in services and the orders list.\n• Accounting: accountants can process supplier invoices and get clear attention states when a processed invoice is changed or deleted.\n• Invoice language: when a manager chooses an invoice language while creating an invoice, the system remembers it for that payer/client.\n• Overdue Payments: dashboard overdue amounts now show the real remaining debt more accurately, excluding cancelled payments and duplicates.\n• Client card saves: invoice language and other client settings now save reliably even when older database fields are not present.","ru":"• Новости релиза: язык новости можно выбрать прямо в pop-up обновления, отдельно от языка интерфейса.\n• Счета поставщиков: загруженные счета можно сопоставлять с реальными услугами заказа, отмечать периодические/необязательные услуги и видеть готовность прямо в услугах и списке заказов.\n• Бухгалтерия: бухгалтеры могут обрабатывать счета поставщиков и получают понятные предупреждения, если обработанный счет изменили или удалили.\n• Язык счета: если менеджер выбирает язык при выставлении счета, система запоминает его для этого плательщика/клиента.\n• Overdue Payments: просроченная задолженность на Dashboard теперь точнее показывает реальный остаток долга, без отменённых платежей и дублей.\n• Карточка клиента: язык счета и другие настройки клиента теперь сохраняются надёжно даже при отсутствии старых полей базы.","lv":"• Relīzes ziņas: ziņu valodu var izvēlēties tieši atjauninājuma logā, neatkarīgi no saskarnes valodas.\n• Piegādātāju rēķini: augšupielādētos rēķinus var sasaistīt ar reāliem pasūtījuma pakalpojumiem, atzīmēt periodiskus/nav nepieciešamus pakalpojumus un redzēt gatavību pakalpojumos un pasūtījumu sarakstā.\n• Grāmatvedība: grāmatveži var apstrādāt piegādātāju rēķinus un saņem skaidrus brīdinājumus, ja apstrādāts rēķins ir mainīts vai dzēsts.\n• Rēķina valoda: ja menedžeris izvēlas rēķina valodu rēķina izveides laikā, sistēma to atceras šim maksātājam/klientam.\n• Overdue Payments: kavēto maksājumu summa panelī tagad precīzāk rāda reālo atlikušo parādu, bez atceltiem maksājumiem un dublikātiem.\n• Klienta karte: rēķina valoda un citi klienta iestatījumi tagad saglabājas droši arī tad, ja vecāki datubāzes lauki nav pieejami."}$m$,
  NULL,
  'system_update:2026-04-27'
FROM public.companies c
ON CONFLICT (company_id, ref_id) DO NOTHING;
